#!/bin/bash

DOCKER_IMAGE="graphql-php"
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function cli-message() {
  printf '\e[36m>>> %s\e[0m\n' "$1"
}

# Build image if it doesn't exist.
if [[ "$(docker images -q ${DOCKER_IMAGE} 2> /dev/null)" == "" ]]; then
  cli-message "Image ${DOCKER_IMAGE} not found, building..."
  docker build -t ${DOCKER_IMAGE}:latest ${SCRIPT_PATH}/../graphql-php
  cli-message "Image build complete, continuing with command..."
fi

# Run in container.
docker run --rm -w /var/www -itv ${SCRIPT_PATH}/../../src/:/var/www ${DOCKER_IMAGE} composer $@